# Generated by Django 5.0.6 on 2024-06-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMFapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=15)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
                ('endereco', models.CharField(max_length=255)),
                ('contato_emergencia', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='profissional',
            old_name='cpf',
            new_name='CPF',
        ),
        migrations.AddField(
            model_name='profissional',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
