# Generated by Django 5.0.6 on 2024-06-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMFapp', '0002_paciente_rename_cpf_profissional_cpf_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profissional',
            old_name='image',
            new_name='foto_de_perfil',
        ),
        migrations.AddField(
            model_name='paciente',
            name='foto_de_perfil',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
