# Generated by Django 5.0.6 on 2024-06-10 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMFapp', '0004_atendente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='data_nascimento',
            new_name='data_de_nascimento',
        ),
        migrations.RenameField(
            model_name='profissional',
            old_name='data_nascimento',
            new_name='data_de_nascimento',
        ),
    ]
